### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by danielramandi** [UBC-MDS/Credit_Approval_Prediction#21]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, excellent work! Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. 
**1. Project set-up**
The directories and overall structure of the repository look great. Here are some suggestions for improvement.

- [x] Files such as .DS_Store should not be committed. -1

**Comment:** This can happen when you push a directory from Mac with all its content. You can easily solve it by adding it to gitignore. Check [here](https://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository).

**2. CONTRIBUTING.md**
I would suggest updating your contributing file so that:

- [x] Contributing documentation should reflect all the ways people can contribute to the project (core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's, as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). -2

**3. README.md**

- [x] The clarity of README could be improved through additional proofreading. -1

**Comment:** I suggest adding your question before the EDA. It is better to first familiarize the reader with what you are trying to do and then talk about the EDA. After the EDA, you can delve a bit deeper into your analysis methodology.

**4. Exploratory data analysis in a literate code document**

- [x] There are no figure captions. -2 viz

- [x] There figure captions for the tables should be above the table. -1 viz

**Comment:** make sure your figures and tables have captions and figure/table numbers, with minimal repetition of information, so that they can be easily referenced in the text. I suggest combining your figures in subplots when they are related (eg. histograms, value counts, etc.). I also suggest that you always colormap your correlation tables or matrices. Also, for the histogram, It’s better to group by class to show if there are any differences in the distributions of features between classes. These are all just suggestions, and not necessary to implement.

- [x] Missing a summary/abstract in the analysis (.ipynb or .Rmd) file -2

- [x] There are no references in the analysis (.ipynb or .Rmd) file -2

**Comment:** The abstract and references do not need to be long, but would help modularize your report.

- [x] The narration of methods and method choices was not as clear and thorough as expected. -1

**Comment:** It is a little unclear what the data types are, and how you figured out A2 and A14 were the only features affected by “?”. It seems like most features contained that missing value. You can either use pandas_profiling or print the head of the dataframe to show the format of the features.

**Overall comment:** The project is well designed and the dataset is chosen wisely to fit the project. The question is clear and the structure of the repo looks good. Well done and good luck with the rest of the project.

**Comment by spencergerlach** [comment]
Thank you Daniel, we'll have these implemented by Milestone 4

**Comment by RussDim** [comment]
Changes made:
1. Project set-up

-  Removed DS_Store files

2.  Contributing file changed : 
- [commit with changes](https://github.com/UBC-MDS/Credit_Approval_Prediction/commit/81f92840219fbbd26392a973cb196f6561b01b5f)

3.  README updated to reflect latest work: 
- [commit with changes](https://github.com/UBC-MDS/Credit_Approval_Prediction/commit/440474269af1ea696b1547999a70855556eb1e59)


4.  EDA improved per feedback:  Added captions, comments.  Improved analysis wording and structure. References added wherever appropriate
- [commit with changes](https://github.com/UBC-MDS/Credit_Approval_Prediction/commit/d44aff188dc9b95de12c38ee5443f684276539e2)
